spring:
  data:
    mongodb:
      uri: mongodb+srv://manuraj23:ShareBite123@cluster0.mqqraew.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: ShareBite
      auto-index-creation: true
server:
  port: 8081
  servlet:
    context-path: /ShareBite